title: "ACUVEG"
description: "Útlum hluku vegetací"

# Site URLs (important for GitHub Pages)
url: "https://vukoz-oel.github.io"
baseurl: "/acuveg_database"

permalink: pretty

theme: minimal-mistakes-jekyll

destination: docs

plugins:
  - jekyll-include-cache

paginate_path: /page:num/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "main"
      pagination: false
      show_prev_next: false

include:
  - _pages
  - assets
  - _includes

footer:
  links: []

locale: cs-CZ
search: true
